# Generated by Django 2.1.4 on 2019-03-03 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_age_start', models.IntegerField()),
                ('target_age_end', models.IntegerField()),
                ('target_gender', models.CharField(max_length=127)),
                ('video_file', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('camera', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('Frame_Shape', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('Image', models.TextField(blank=True, default=None, null=True)),
                ('Gender', models.CharField(max_length=20)),
                ('Location', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Ads')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('tag_id', models.CharField(max_length=128)),
                ('image', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TagHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=128)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Data')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Tag')),
            ],
        ),
    ]
