# Generated by Django 2.1.5 on 2019-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='helper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=20)),
                ('Age_of_person', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='x',
        ),
    ]
