# Generated by Django 2.1.4 on 2019-03-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Ads')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector.Data')),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='person',
        ),
        migrations.RemoveField(
            model_name='target',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
