# Generated by Django 2.1.4 on 2019-03-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20190303_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='campaign_name',
            field=models.CharField(default='-', max_length=127),
        ),
    ]
