# Generated by Django 2.1.5 on 2019-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20190201_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=20)),
                ('Age', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='x',
        ),
    ]
