# Generated by Django 2.1.5 on 2019-02-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_data_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Timestamp',
            field=models.CharField(default='000000', max_length=250),
        ),
        migrations.AddField(
            model_name='data',
            name='head_pitch',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='head_roll',
            field=models.FloatField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='head_yaw',
            field=models.FloatField(default=0, max_length=200),
        ),
    ]
