# Generated by Django 2.1.5 on 2019-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20190203_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Frame_Shape',
            field=models.CharField(default=[0, 0, 0], max_length=150),
        ),
        migrations.AddField(
            model_name='data',
            name='Image',
            field=models.CharField(default='images1', max_length=150),
        ),
        migrations.AddField(
            model_name='data',
            name='Location',
            field=models.CharField(default='images/', max_length=300),
        ),
        migrations.AlterField(
            model_name='data',
            name='Age',
            field=models.IntegerField(default='NA'),
        ),
        migrations.AlterField(
            model_name='data',
            name='Gender',
            field=models.CharField(default='NA', max_length=20),
        ),
        migrations.AlterField(
            model_name='data',
            name='head_pitch',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='data',
            name='head_roll',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='data',
            name='head_yaw',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='data',
            name='image_name',
            field=models.CharField(max_length=150),
        ),
    ]
