# Generated by Django 2.1.5 on 2019-02-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0008_auto_20190227_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Timestamp',
            field=models.DateTimeField(default='000000', max_length=250),
        ),
    ]
